spring:
  profiles:
    active: test

  application:
    name: "demo-fin-app"

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: false

  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

app:
  timezone: UTC

server:
  port: 8080